#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pygame, random


class Snake():
    def __init__(self):
        pygame.init()

        self.gameDisplay = pygame.display.set_mode((800,600))
        gameDisplayColour = (30, 144, 255)

        pygame.display.set_caption('Bald Seva')

        gameExit = False

        lead_x = 400
        lead_y = 270
        lead_x_change = 0
        lead_y_change = 0

        clock = pygame.time.Clock()

        while not gameExit:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    gameExit = True
                try:
                    if event.type == pygame.KEYDOWN:
                        x_val = {pygame.K_LEFT: -2,
                            pygame.K_RIGHT: 2}
                        lead_x_change = x_val[event.key]
                        lead_y_change = 0
                except:
                    y_val = {273: -2,
                                274: 2}
                    lead_y_change = y_val[event.key]
                    lead_x_change = 0

            lead_x += lead_x_change
            lead_y += lead_y_change
            if abs(lead_x) >= 790 or abs(lead_x) <= 0:
                lead_x_change = 0
                self.lose()
                break
            if abs(lead_y) >= 590 or abs(lead_y) <= 0:
                lead_y_change = 0
                self.lose()
                break

            self.gameDisplay.fill(gameDisplayColour)
            pygame.draw.rect(self.gameDisplay, (0, 0, 0), [lead_x, lead_y, 15, 15])
            self.blocks()
            pygame.display.update()

            clock.tick(100)

    def blocks(self):

        ran_x_block_pos = random.randint(0, 800)
        ran_y_block_pos = random.randint(0, 600)

        pygame.draw.rect(self.gameDisplay, (0,255,0), [ran_x_block_pos, ran_y_block_pos, 10, 10])

        
    def lose(self):
        try:
            self.gameDisplay.draw.rect('Game Over! You lose!')
        except:
            print("Congrats! You lose!")



obj_1 = Snake()
pygame.quit()
quit()
